CREATE SEQUENCE PRIMARY_KEY_SEQUENCE START WITH 1 INCREMENT BY 1 NOCYCLE;

CREATE TABLE STATE_CITY
(
    STATE_CITY_ID      NUMBER(18, 0) PRIMARY KEY ,
    STATE              VARCHAR2(30) NOT NULL,
    CITY               VARCHAR2(30) NOT NULL,
    CREATED_BY         VARCHAR2(50),
    CREATED_DATE       DATE,
    LAST_MODIFIED_BY   VARCHAR2(50),
    LAST_MODIFIED_DATE DATE,
    VERSION            NUMBER(18, 0),
    XML                BLOB
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID        NUMBER(18, 0) PRIMARY KEY,
    FIRST_NAME         VARCHAR2(30)  NOT NULL,
    MIDDLE_NAME        VARCHAR2(30),
    LAST_NAME          VARCHAR2(30)  NOT NULL,
    DOB                DATE          NOT NULL,
    GENDER             VARCHAR2(10)   NOT NULL,
    PHONE_NUMBER       VARCHAR2(10)  NOT NULL,
    EMAIL              VARCHAR2(30),
    MARITAL_STATUS     VARCHAR2(10)  NOT NULL,
    FATHER_NAME        VARCHAR2(50),
    MOTHER_NAME        VARCHAR2(50),
    PRESENT_ADDRESS    VARCHAR2(500) NOT NULL,
    PERMANENT_ADDRESS  VARCHAR2(500) NOT NULL,
    STATE_CITY_ID      NUMBER(18,0) REFERENCES STATE_CITY,
    PIN_CODE           VARCHAR2(6)   NOT NULL,
    PROFILE_IMAGE      BLOB,
    SIGNATURE          BLOB,
    PAN_CARD           BLOB,
    ID_PROOF           BLOB,
    ADDRESS_PROOF      BLOB,
    DESCRIPTION        VARCHAR2(500),
    XML                BLOB,
    CREATED_BY         VARCHAR2(50),
    CREATED_DATE       DATE,
    LAST_MODIFIED_BY   VARCHAR2(50),
    LAST_MODIFIED_DATE DATE,
    VERSION            NUMBER(18,0)
);

CREATE TABLE INTEREST_RATE
(
    INTEREST_RATE_ID   NUMBER(18, 0) PRIMARY KEY,
    INTEREST_RATE      VARCHAR2(10),
    MONTHS             VARCHAR2(10),
    YEARS              VARCHAR2(10),
    DAYS               VARCHAR2(10),
    XML                BLOB,
    CREATED_BY         VARCHAR2(50),
    CREATED_DATE       DATE,
    LAST_MODIFIED_BY   VARCHAR2(50),
    LAST_MODIFIED_DATE DATE,
    VERSION            NUMBER(18, 0)
);