spring:
  application:
    name: manage-discovery-server

server:
  port: 8761

management:
  server:
    port: 8762
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
