spring:
  application:
    name: spring-boot-security
  datasource:
    username: V705417
    password: V705417
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE

server:
  port: 8081

