spring:
  application:
    name: spring-boot-security
  datasource:
    username: V705417
    password: V705417
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
  jpa:
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
